backend:
  name: git-gateway
  branch: master

media_folder: "static/media/image"
public_folder: "/media/image"
# publish_mode: "editorial_workflow"

collections:

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    # Disable preview
    editor:
      preview: false

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}


